

//--------------------------------------------------
//
//	JS RANDOM BANNER
//
//--------------------------------------------------
function banner_main(pid) {
	 if (pid.indexOf("jannott")==0) { document.write('blabla'); }
	 		else if (pid.indexOf("SW04_09")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=30890&pageid=SW04_09&loc=profile&ban=benjamin_ar3.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/benjamin_ar3.gif?coid=30890&pageid=SW04_09%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("dd04_09")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=30890&pageid=dd04_09&loc=profile&ban=benjamin_ar4.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/benjamin_ar4.gif?coid=30890&pageid=dd04_09%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("bimdiv0409")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=31835&pageid=bimdiv0409&loc=profile&ban=daltile2.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/daltile2.gif?coid=31835&pageid=bimdiv0409%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("SW04_00")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=32063&pageid=SW04_00&loc=profile&ban=draper.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/draper.gif?coid=32063&pageid=SW04_00%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("sd04010")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=32505&pageid=sd04010&loc=profile&ban=travisin.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/travisin.gif?coid=32505&pageid=sd04010%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("dd04_07")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=33038&pageid=dd04_07&loc=profile&ban=malarkey.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/malarkey.gif?coid=33038&pageid=dd04_07%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("div0404")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=33748&pageid=div0404&loc=http://www.laticrete.com/mvis/&ban=laticret.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/laticret.gif?coid=33748&pageid=div0404%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("sd04008")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=34626&pageid=sd04008&loc=profile&ban=overdoor2.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/overdoor2.gif?coid=34626&pageid=sd04008%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("bim099000")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=34943&pageid=bim099000&loc=profile&ban=kellymoo.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/kellymoo.gif?coid=34943&pageid=bim099000%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("div0409")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=35301&pageid=div0409&loc=profile&ban=zinsser.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/zinsser.gif?coid=35301&pageid=div0409%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("bim04_00")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=35322&pageid=bim04_00&loc=profile&ban=armortex.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/armortex.gif?coid=35322&pageid=bim04_00%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("bimdiv0407")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=36454&pageid=bimdiv0407&loc=profile&ban=watsonbo.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/watsonbo.gif?coid=36454&pageid=bimdiv0407%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("dd04_00")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=38425&pageid=dd04_00&loc=http://www.gaf.com/Roofing/Commercial/Products/Single_Ply_Roofing/EverGuard_TPO_Single_Ply_Membranes&ban=gaf.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/gaf.gif?coid=38425&pageid=dd04_00%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("dd04_26")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=40389&pageid=dd04_26&loc=profile&ban=fsrinc.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/fsrinc.gif?coid=40389&pageid=dd04_26%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("div0426")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=40389&pageid=div0426&loc=profile&ban=fsrinc.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/fsrinc.gif?coid=40389&pageid=div0426%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("bimdiv0411")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=40389&pageid=bimdiv0411&loc=profile&ban=fsrinc.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/fsrinc.gif?coid=40389&pageid=bimdiv0411%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("bp04_00")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=40601&pageid=bp04_00&loc=profile&ban=keyresin.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/keyresin.gif?coid=40601&pageid=bp04_00%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("div0407")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=41461&pageid=div0407&loc=profile&ban=bluewatm.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/bluewatm.gif?coid=41461&pageid=div0407%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("sd04007")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=43515&pageid=sd04007&loc=http://www.stucoflex.com/rainscreen_drainage_mats.html&ban=stucofle.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/stucofle.gif?coid=43515&pageid=sd04007%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("bim083400")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=43992&pageid=bim083400&loc=http://www.dynacodoor.us/%3Futm_source=directory%26utm_medium=online%26utm_campaign=arcat&ban=dynaco.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/dynaco.gif?coid=43992&pageid=bim083400%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("bimdiv0408")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=43992&pageid=bimdiv0408&loc=http://www.dynacodoor.us/%3Futm_source=directory%26utm_medium=online%26utm_campaign=arcat&ban=dynaco.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/dynaco.gif?coid=43992&pageid=bimdiv0408%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("sd04009")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=44427&pageid=sd04009&loc=profile&ban=rodda.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/rodda.gif?coid=44427&pageid=sd04009%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("div0405")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=47628&pageid=div0405&loc=profile&ban=safrail2.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/safrail2.gif?coid=47628&pageid=div0405%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
	 		else if (pid.indexOf("sd04_00")==0) { document.write('<A HREF="http://www.arcat.com/clickthru.pl?coid=49219&pageid=sd04_00&loc=profile&ban=termfor2.gif&mf=04"><IMG SRC="http://www.arcat.com/banner/gfx/termfor2.gif?coid=49219&pageid=sd04_00%20" ALT="Click for Additional Info" border=0 class="img-responsive"></A>'); banner_displayed=1; }
}
//--------------------------------------------------
			
