

//import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ba Boo
 */
import java.sql.*;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
public class Sale extends javax.swing.JFrame {
 Connection conn;
 ResultSet rs;
 PreparedStatement pst;
    /**
     * Creates new form Sale
     */
    public Sale() {
        super("Smart CamTeCH Version 1.0");
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Logo.png")));
        setResizable(false);
        conn=javaconnection.ConnecrDb();
        comBind();
        jcom();
        Update_table();
        
    }
      public void showDetail(){
     try{
         int row=jTable1.getSelectedRow();
         String click=(jTable1.getModel().getValueAt(row, 0).toString());
         String sql="Select Pro_ID,Pro_Name,Category,Quantity,Sale_Unit,Amount from sale_detail where Sale_ID='"+click+"'";
         pst=conn.prepareStatement(sql);
         rs=pst.executeQuery();
         jTable2.setModel(DbUtils.resultSetToTableModel(rs));
         try{
             String sql1="Select Amount from shopdatabase.`Sale` where Sale_ID='"+click+"'";
             pst=conn.prepareStatement(sql1);
             rs=pst.executeQuery();
             while(rs.next()){
                // if(rs.getString("Order_ID").equals(click)){
                 //lbl_total1.setText("Total Amount      :  ");
                txt_total.setText(rs.getString("Amount"));
                // }
             }
         }catch(Exception e){
//            JOptionPane.showMessageDialog(null,e);
         }
          }catch(Exception e){
//         JOptionPane.showMessageDialog(null,e);
     }
        
 }
    
     public void Update_table()
    {
        try{
            pst=conn.prepareStatement("SELECT Sale_ID,Staff_ID,Date,Amount FROM shopdatabase.sale");
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            //CountCus();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
            public void jcom()
{
    try{
        String x="Active";
        String y="Cleaner";
        String z="Security";
    String SQL="select * from emp where status='Active' and position!='Cleaner'and position!='Security';";//"select * from emp where status='"+x+"' AND position!='"+y+"' AND position!='"+z+"'";
    pst=conn.prepareStatement(SQL);
    rs=pst.executeQuery();
        while(rs.next())
        {
            cbo_emp.addItem(rs.getString("id"));
        }
    }catch(Exception e)
    {
        JOptionPane.showMessageDialog(null,"JComcobox function :"+e);
    }
}

     public void comBind(){
      javaconnection mq=new javaconnection();
      Connection con=mq.ConnecrDb();
      Statement st;
      try{
          st=con.createStatement();
          rs=st.executeQuery("Select Product_ID from product");
          //String sql="Select Product_ID from product";
          while(rs.next()){
              //int item[]={rs.getInt(1)};
            //  int T=rs.getInt(1);
              cbo_PID.addItem(rs.getString(1));
              
          }
          
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
      }finally{
          try{
              String sql="select * from product where Product_ID='"+(String)cbo_PID.getSelectedItem()+"'";
              pst=conn.prepareStatement(sql);
              rs=pst.executeQuery();
              if(rs.next()){
                  txt_name.setText(rs.getString(3));
                  txt_cat.setText(rs.getString(2));
                  txt_unit.setText(rs.getString(5));
                  
              }
          }catch(Exception e){
              JOptionPane.showMessageDialog(null,e);
          }
      }
      
      
  } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txt_total = new javax.swing.JTextField();
        btn_insert = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cbo_emp = new javax.swing.JComboBox<>();
        txt_sale = new javax.swing.JTextField();
        txt_date = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_cat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbo_PID = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_qty = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_unit = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jTable2.setForeground(new java.awt.Color(153, 0, 51));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pro_ID", "Pro_Name", "Category", "Quantity", "Sale_Unit", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 0));
        jLabel7.setText("Grand Total    :");

        txt_total.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txt_total.setForeground(new java.awt.Color(102, 102, 0));

        btn_insert.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        btn_insert.setForeground(new java.awt.Color(153, 0, 0));
        btn_insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons_Button/Shopping-cart-insert-icon.png"))); // NOI18N
        btn_insert.setText("Insert");
        btn_insert.setEnabled(false);
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(153, 0, 0));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons_Button/Delete-icon.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setEnabled(false);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_save.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        btn_save.setForeground(new java.awt.Color(153, 0, 0));
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons_Button/Save_ico.png"))); // NOI18N
        btn_save.setText("Save");
        btn_save.setEnabled(false);
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_back.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        btn_back.setForeground(new java.awt.Color(153, 0, 0));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons_Button/Go-back-icon.png"))); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_close.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        btn_close.setForeground(new java.awt.Color(153, 0, 0));
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons_Button/Close-icon.png"))); // NOI18N
        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        btn_new.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        btn_new.setForeground(new java.awt.Color(153, 0, 0));
        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons_Button/New_ico.png"))); // NOI18N
        btn_new.setText("New");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        txt_search.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txt_search.setForeground(new java.awt.Color(102, 102, 0));
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        jPanel1.setEnabled(false);

        cbo_emp.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        cbo_emp.setForeground(new java.awt.Color(153, 0, 51));
        cbo_emp.setEnabled(false);

        txt_sale.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txt_sale.setForeground(new java.awt.Color(102, 102, 0));
        txt_sale.setEnabled(false);

        txt_date.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 0));
        jLabel2.setText("Staff_ID");

        txt_name.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txt_name.setForeground(new java.awt.Color(102, 102, 0));
        txt_name.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 0));
        jLabel6.setText("Pro_Name");

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("Sale_ID");

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 0));
        jLabel3.setText("Date");

        txt_cat.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txt_cat.setForeground(new java.awt.Color(102, 102, 0));
        txt_cat.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 0));
        jLabel5.setText("Category");

        cbo_PID.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        cbo_PID.setForeground(new java.awt.Color(153, 0, 51));
        cbo_PID.setEnabled(false);
        cbo_PID.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbo_PIDPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 0));
        jLabel4.setText("Pro_ID");

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 0));
        jLabel8.setText("Quantity");

        txt_qty.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txt_qty.setForeground(new java.awt.Color(102, 102, 0));
        txt_qty.setEnabled(false);
        txt_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_qtyKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 0));
        jLabel9.setText("Sale_Unit");

        txt_unit.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        txt_unit.setForeground(new java.awt.Color(102, 102, 0));
        txt_unit.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(cbo_emp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(txt_sale, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_qty))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbo_PID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_cat)
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sale, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_emp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_date, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbo_PID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_unit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(153, 0, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sale_ID", "Staff_ID", "Date", "Total"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Shop Management\\Images\\lo1new.png")); // NOI18N

        jLabel11.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setText("Sale Information");

        jLabel12.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 0));
        jLabel12.setText("Search Here :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_close)))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(111, 111, 111)
                        .addComponent(jLabel11)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(891, 576));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tMOdel = (DefaultTableModel) jTable2.getModel();
        //tMOdel.setRowCount(0);
         int i = 0;
int rowcount= jTable2.getRowCount();
          if(txt_date.getDate()==null){ JOptionPane.showMessageDialog(null,"Please Select Date!!!");
          txt_date.requestFocus();
        }else if(txt_qty.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please Input QTY!!!");
            txt_qty.requestFocus();
        }
        else{
            
           Integer ID = Integer.parseInt((String)cbo_PID.getSelectedItem().toString().trim());
           mode=(DefaultTableModel)jTable2.getModel();
           
           //JOptionPane.showMessageDialog(null,"Item has Inserted");
          
           if(rowcount>0){
           for(i=0; i<rowcount; i++){
               //JOptionPane.showMessageDialog(null,""+ID+"\n"+jTable2.getModel().getValueAt(i,0)); 
               int idcompare=Integer.parseInt(jTable2.getValueAt(i, 0).toString());
               if(ID==idcompare){
                   JOptionPane.showMessageDialog(null,"Item has Inserted");
                   return;
               }        
           }
           }
           if(rowcount==i){     
                try{
                    Float QT=Float.parseFloat(txt_qty.getText());
                    String sql="select Quantity from product where Product_ID='"+(String)cbo_PID.getSelectedItem()+"'";
                    pst=conn.prepareStatement(sql);
                    rs=pst.executeQuery();
                    while(rs.next()){
                        Float QY=rs.getFloat("Quantity");//Float.parseFloat(rs.getString("Quantity"));
                        if(QY<QT){
                            JOptionPane.showMessageDialog(null,"Not Enough Product In stock\n Product in Stock only have "+QY);
                        }else if(QY>=QT){
                                 try{

            DecimalFormat doll=new DecimalFormat("#,##0.00");
            String Cat=txt_cat.getText();
            String id=(String)cbo_PID.getSelectedItem();
            String name=txt_name.getText();
            String unit=txt_unit.getText();
            String qty=txt_qty.getText();
            Float Q=Float.parseFloat(txt_qty.getText());
            Float U=Float.parseFloat(txt_unit.getText());
            Float A=Q*U;
            String UN="$ "+doll.format(U);
            String QTY=doll.format(Q)+" PCS";
            DecimalFormat dol=new DecimalFormat("0.00");
            String amount=""+dol.format(A);
            DefaultTableModel mod=(DefaultTableModel)jTable2.getModel();
            String row[]={id,name,Cat,QTY,UN,amount};
            mod.addRow(row);
              double sum=0;
        DecimalFormat dollar = new DecimalFormat("#,##0.00");
        try{
           for(i=0;i<jTable2.getRowCount();i++){
               sum=sum+Float.parseFloat((String) jTable2.getValueAt(i,5)); 
           }
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        String F="$"+dollar.format(sum);
      /*  float deposit=(float) (sum/2);
        String de="$ "+dollar.format(deposit);
        txt_deposit.setText(de);
        txt_balance.setText(de);*/
        txt_total.setText(F);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
                        }
                    }
                }catch(Exception e){
                            JOptionPane.showMessageDialog(null,e);
                            }
     
        
           }
        }  
              
    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // TODO add your handling code here:
        btn_insert.setEnabled(true);
        txt_sale.setEnabled(false);
        //txt_name.setEnabled(true);
        btn_save.setEnabled(true);
        cbo_PID.setEnabled(true);
        txt_qty.setEnabled(true);
        txt_qty.requestFocus();
        //txt_unit.setEnabled(true);
        //txt_cat.setEnabled(true);
        cbo_emp.setEnabled(true);
        txt_date.setEnabled(true);
         DefaultTableModel tMOdel = (DefaultTableModel) jTable2.getModel();
        tMOdel.setRowCount(0);
         try{
           
            String sql="SELECT max(Sale_id) FROM shopdatabase.sale";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                int S=rs.getInt(1)+1;
                String s=""+S;
                txt_sale.setText(s);
           
            }
            
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btn_newActionPerformed

    private void cbo_PIDPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbo_PIDPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
         String S=(String)cbo_PID.getSelectedItem();
        String sql="select * from product where Product_ID='"+S+"'";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                txt_name.setText(rs.getString(3));
                txt_cat.setText(rs.getString(2));
                txt_unit.setText(rs.getString(5));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_cbo_PIDPopupMenuWillBecomeInvisible

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        /*     String s;  
        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
        String date=sdf.format(txt_date.getDate());
        DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        try{
           // s = DecimalFormat.getCurrencyInstance(Locale.getDefault()).parse (txt_total.getText()).toString();   
            //double d=Double.valueOf(txt_total.getText().replace("$",""));
            String sql="insert into sale values('"+txt_sale.getText()+"','"+(String)cbo_emp.getSelectedItem()+"','"+date+"','"+txt_total.getText()+"')";
            pst=conn.prepareStatement(sql);
            pst.execute();
          //   JOptionPane.showMessageDialog(null, "Inserted into Import Table!!");
            try{
                 model=(DefaultTableModel) jTable2.getModel();
                for(int i=0;i<model.getRowCount();++i){
                    //for()
                    String sql1="insert into sale_detail(Sale_ID,Pro_ID,Product_Name,Category,Sale_Unit,Amount) "
                            + "values('"+txt_sale.getText()+"','"+(String) model.getValueAt(i,0)+"','"+(String) model.getValueAt(i,1)+"'"
                            + ",'"+(String) model.getValueAt(i,2)+"','"+(String) model.getValueAt(i,3)+"','"+(String) model.getValueAt(i,4)+"','"+(String) model.getValueAt(i,5)+"')";
                   /* pst.setString(1,txt_import_id.getText());
                    pst.setString(2,(String) model.getValueAt(i,0));
                    pst.setString(3,(String) model.getValueAt(i,1));
                    pst.setString(4,(String) model.getValueAt(i,2));
                    pst.setString(5,(String) model.getValueAt(i,3));
                    pst.setString(6,(String) model.getValueAt(i,4));
                    pst.setString(7,(String) model.getValueAt(i,5));*/
   /*                 pst=conn.prepareStatement(sql1);
                    pst.executeUpdate();
                    Update_table();
                    //pst.close();
                   // conn.close();
                   
                   try{
                       String sq1="select * from product";
                   pst=conn.prepareStatement(sq1);
                   rs=pst.executeQuery();
                   String D=(String)model.getValueAt(i,0).toString();
                   
                   while(rs.next()){
                   if(D.equals(rs.getString("Product_ID"))){
                       Float Q=Float.parseFloat(model.getValueAt(i,4).toString().replaceAll("pcs",""));
                       Float A=rs.getFloat("Quantity");
                       Float X=A+Q;
                       String sq2="update product set Quantity='"+X+"' where Product_ID='"+D+"'";
                       pst=conn.prepareStatement(sq2);
                       pst.executeUpdate();
                      // JOptionPane.showMessageDialog(null,"Product Updated!!");
                   }
                   }
                   }catch(Exception e){
                       JOptionPane.showMessageDialog(null,"Update"+e);
                   }
                   
                }
                JOptionPane.showMessageDialog(null,"Successfully");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }*/
   
        try{
            DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
         String date=sdf.format(txt_date.getDate());
            String sql="INSERT INTO `shopdatabase`.`sale` (`Sale_ID`, `Staff_ID`, `Date`, `Amount`) VALUES ('"+txt_sale.getText()+"', '"+(String)cbo_emp.getSelectedItem()+"','"+date+"','"+txt_total.getText()+"')";
           // String //sql="insert into order valuesINSERT INTO `shopdatabase`.`order` (`Order_ID`, `Staff_id`, `Cus_id`, `Total_Amount`, `Date`, `Deposit`, `Balance`) VALUES('"+txt_order.getText()+"','"+(String)cbo_emp.getSelectedItem()+"'"
                  //  + ",'"+(String)cbo_cus.getSelectedItem()+"','"+txt_total.getText()+"','"+date+"','"+txt_deposit.getText()+"','"+txt_balance.getText()+"')";
                  //  + "('"+txt_order.getText()+"','"+(String)cbo_emp.getSelectedItem()+"','"+(String)cbo_cus.getSelectedItem()+"',"
                    //+ "'"+txt_total.getText()+"','"+date+"','"+txt_deposit.getText()+"','"+txt_balance.getText()+"')";
            pst=conn.prepareStatement(sql);
            pst.executeUpdate();
          JOptionPane.showMessageDialog(null,"Information has been saved!!");
            try{
                DefaultTableModel mod=(DefaultTableModel)jTable2.getModel();
                for(int i=0;i<jTable2.getRowCount();++i){
                     String sql1="insert into sale_detail values('"+txt_sale.getText()+"','"+(String)mod.getValueAt(i,0)+"',"
                             + "'"+(String)mod.getValueAt(i,1)+"','"+(String)mod.getValueAt(i,2)+"','"+(String)mod.getValueAt(i,3)+"','"+(String)mod.getValueAt(i,4)+"','"+(String)mod.getValueAt(i,5)+"')";
                     pst=conn.prepareStatement(sql1);
                     pst.executeUpdate();
                     try{
                       String sq1="select * from product";
                   pst=conn.prepareStatement(sq1);
                   rs=pst.executeQuery();
                   String D=(String)model.getValueAt(i,0).toString();
                   while(rs.next()){
                   if(D.equals(rs.getString("Product_ID"))){
                       Float Q=Float.parseFloat(model.getValueAt(i,3).toString().replaceAll("PCS",""));
                       Float A=rs.getFloat("Quantity");
                       Float X=A-Q;
                       String sq2="update product set Quantity='"+X+"' where Product_ID='"+D+"'";
                       pst=conn.prepareStatement(sq2);
                       pst.executeUpdate();
                      // JOptionPane.showMessageDialog(null,"Product Updated!!");
                      Update_table();
                   }
                   }
                   }catch(Exception e){
                       JOptionPane.showMessageDialog(null,"Update"+e);
                   }
                    // JOptionPane.showMessageDialog(null,"Inserted into Import Detail!!");
                }
               
            }catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"No OK!!"+e);
        }    
 
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        setVisible(false);
        Home ob=new Home();
        ob.setVisible(true);
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        setVisible(false);
    }                                         

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void cbo_proActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void cbo_proPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {                                                     
        // TODO add your handling code here:
          String S=(String)cbo_PID.getSelectedItem();
        String sql="select * from product where Product_ID='"+S+"'";
        try{
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                txt_name.setText(rs.getString(3));
                txt_cat.setText(rs.getString(2));
                txt_unit.setText(rs.getString(5));
                
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_btn_saveActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        showDetail();
        btn_delete.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        showDetail();
        btn_delete.setEnabled(true);
    }//GEN-LAST:event_jTable1KeyPressed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
     try {
         // TODO add your handling code here:
         int row=jTable1.getSelectedRow();
         String click=(jTable1.getModel().getValueAt(row, 0).toString());
         String sql="DELETE FROM sale where Sale_ID='"+click+"'";
         pst=conn.prepareStatement(sql);
         pst.executeUpdate();
         Update_table();
         JOptionPane.showMessageDialog(null,"Information has been deleted!!");
     } catch (SQLException ex) {
         Logger.getLogger(Sale.class.getName()).log(Level.SEVERE, null, ex);
     }
        
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home ob=new Home();
        ob.setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_closeActionPerformed
DefaultTableModel mode;
    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
          
                 try{
        mode=(DefaultTableModel)jTable1.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(((DefaultTableModel) jTable1.getModel())); 
        sorter.setRowFilter(RowFilter.regexFilter(txt_search.getText()));
        jTable1.setRowSorter(sorter);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);   
         }
        
    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtyKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
if(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)|| (c==KeyEvent.VK_DELETE))
{
} else {
    getToolkit().beep();
    evt.consume();
        }
    }//GEN-LAST:event_txt_qtyKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_insert;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cbo_PID;
    private javax.swing.JComboBox<String> cbo_emp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txt_cat;
    private com.toedter.calendar.JDateChooser txt_date;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_qty;
    private javax.swing.JTextField txt_sale;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txt_unit;
    // End of variables declaration//GEN-END:variables
}
